-- MySQL Script generated by MySQL Workbench
-- 12/12/16 21:33:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gfinanceiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gfinanceiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gfinanceiro` DEFAULT CHARACTER SET latin1 ;
USE `gfinanceiro` ;

-- -----------------------------------------------------
-- Table `gfinanceiro`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gfinanceiro`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `dtaCadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ativo` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gfinanceiro`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gfinanceiro`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ativo` INT(11) NOT NULL DEFAULT '1',
  `saldo` DECIMAL(7,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gfinanceiro`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gfinanceiro`.`fornecedor` (
  `idfornecedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL DEFAULT NULL,
  `cnpj` VARCHAR(18) NULL DEFAULT NULL,
  `ativo` INT(11) NOT NULL DEFAULT '1',
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idfornecedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gfinanceiro`.`movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gfinanceiro`.`movimentacao` (
  `idmovimentacao` INT(11) NOT NULL AUTO_INCREMENT,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `valor` DECIMAL(7,2) NULL DEFAULT NULL,
  `tipo_movimentacao` INT(11) NOT NULL COMMENT 'Exemplo: 1 para entrada 2 para saída',
  `dsc` TEXT NULL DEFAULT NULL,
  `fornecedor_idfornecedor` INT(11) NULL DEFAULT NULL,
  `cliente_idcliente` INT(11) NULL DEFAULT NULL,
  `categoria_idcategoria` INT(11) NOT NULL,
  `ativo` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idmovimentacao`),
  INDEX `fk_movimentacao_fornecedor_idx` (`fornecedor_idfornecedor` ASC),
  INDEX `fk_movimentacao_cliente1_idx` (`cliente_idcliente` ASC),
  INDEX `fk_movimentacao_categoria1_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_movimentacao_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `gfinanceiro`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `gfinanceiro`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_fornecedor`
    FOREIGN KEY (`fornecedor_idfornecedor`)
    REFERENCES `gfinanceiro`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gfinanceiro`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gfinanceiro`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `usuario` VARCHAR(100) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `ativo` VARCHAR(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
